name: Build LaTeX document and upload to Release

on:
  push:
    tags:
      - 'v*' # Triggers the workflow when a tag starting with 'v' is pushed (e.g., v1.0.0)

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for writing to releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex # Replace 'main.tex' with your root LaTeX file name

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf # Replace 'main.pdf' with the name of the generated PDF file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
